Sherlocke has an office at home, but the general public is not going to see much of that.  People with the need, or an invitation and either a valid SIN, or the ability to negotiate the level of security for the area can try for admittance.  Once there, they can admire the replication / emulation of the sitting-room described in the literature, and shown in various forms on multiple trid (and earlier) shows while visiting, or discussing business.  This is a living space, but here are many authentic and copied Sherlocke Holmes memorabilia items to be seen, mixed with collectibles related to other fictional detectives.  The items are not on display as they would be in a museum.  The more expensive items are discretely protected from damage, but the layout has been designed to simply incorporate them into the living space.  This is not a no tech throwback environment either.  AR is used to enhance and extend the room.  Those interested can open unobtrusive deerstalker hat and pipe ARO icons to view the history of the physical and virtual items.

in use replicas
* decanter with real brandy
* tea serving set

The official office for Sherlocke Investigations is similar.  It too is based on the sitting room.  There is no physical desk to sit at.  Instead, comfortable replica period furniture is provided.  Those without an appointment will be greeted by a holo projected secretary in period costume.  There will typically be evidence of some mundane task that the Lady of the house interrupted to greet the guest.

The office area is magically warded, and wi-fi blocked for privacy.  Holmes does not spend a lot of time in the office, except for scheduled meetings.  Instead, he is usually out working on something or other, or just talking to 'interesting' people from any walk of life.
